#include "constants.h"
#include <time.h>

int NUM_PARTICLES = 5;
double MIN_PARTICLE_RADIUS = 0.5;
double MAX_PARTICLE_RADIUS = 1.0;
double MIN_VELOCITY = 5;
double MAX_VELOCITY = 20;
double X_DIMENSION_SIZE = 30;
double Y_DIMENSION_SIZE = X_DIMENSION_SIZE;
double Z_DIMENSION_SIZE = X_DIMENSION_SIZE;
int SEED = time(0);
int MAX_QUEUE_SIZE = QUEUE_SIZE_MULTIPLIER * NUM_PARTICLES;
int TIMESTEP_LIMIT = -1;
int FRAMERATE = 60;
double LOOKAHEAD_TIME = 0.5;
double MAX_LOOKAHEAD_TIME = ((double)QUEUE_SIZE_MULTIPLIER) / FRAMERATE;

int LOOKAHEAD_TIMESTEPS = LOOKAHEAD_TIME * FRAMERATE;

// QUADTREE
int MAX_PARTICLES_PER_LEVEL = 2;
int MAX_LEVELS = 6;

double GRAVITY = 0.000000067;
